while (my $line = <DATA>) {
chomp $line;
print "rsync -Pavz rsync://dev.worldpossible.org/rachelmods/$line/ ./$line/\n";
}

__DATA__
en-local_content
en-teachertraining
en-wikipedia_for_schools
en-moodle
en-kalite
en-fairshake
en-fantasticphonics-adult
en-fantasticphonics-child
en-law_library
en-oya
en-oya-static
en-learnsaylor
en-rachelcourses
en-boundless
en-coreknowledge
en-ck12
en-openstax
en-saylor
en-siyavula
en-GCF2015
en-careergirls
en-blockly-games
en-PhET
en-powertyping
en-understanding_algebra
en-algebra2go
en-math_expression
en-edison
hi-arvind
en-scale-of-universe
en-radiolab
en-TED
en-musictheory
en-olpc
en-peacebuilding
en-ebooks
en-catdogbooks
en-mustardseedbooks
en-bookdash
en-oerafrica-reading
en-binofino
en-afristory
en-iicba
en-wikibooks
en-wikisource
en-wikiversity
en-women-in-african-history
es-guias
es-GCF2015
es-kalite
es-blockly_games
es-cnbguatemala
es-phet-zim
es-soluciones
es-vedoque
es-bibliofilo
es-biblioteca
es-ebooks
es-educalab
es-JuegosDDHH
es-mustardseedbooks
es-tocomadera
es-guatemala
es-ap_didact
fr-kalite
fr-blockly-games
fr-wikipedia_for_schools
fr-phet-haiti
fr-women-in-african-history
fr-wikibooks
fr-wikisource
fr-wikivoyage
fr-wikiversity
fr-afrique-marie-wabbes
fr-bouquineux
fr-catdogbooks
fr-ebooksgratuits
fr-gutenberg
